version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: vehicles-db
    environment:
      POSTGRES_DB: vehicles_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - vehicles_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ms-vehicles
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vehicles_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_ENABLED: "false"
    depends_on:
      - db

volumes:
  vehicles_data: